### ISSUE TITLE
Other vs unknown category.

### ISSUE THREAD

**Issue by livep2000** [andersevenrud/OS.js-v2#109]
It seems i'm responsible for the little buggy's.

A package, that is not registred in one of the known categories, always comes in category 'unknown'.
Following parts of the script, i saw that there is also a category 'Other'.

1. Wouldn't it be nicer if all unknown comes in Other?
2. How about creating a new categorie if unknown?

Imre

**Comment by MrSchism** [comment]
Installing to Other would work, but only if the category could be changed and the menu would reflect it without a session restart.

For it to install into a new category, that would require the categories to be populated from a survey of all listed categories in packages.  This might not be the best way because a maintainer may change the name of a category; giving that arbitrary control of your install to a bunch of people (package developers) might not be in the best interest of the end user.  If a package doesn't fall into a system defined category, it should be placed in 'other' unless the user (or admin, depending on the use case) defines a new category manually.

**Comment by andersevenrud** [comment]
There is no "other" category. I think you might looked at the icon name ;)

This category list was lifted straight from GTK/Gnome.

```
  33   var DefaultCategories = {
  34     development : {icon: 'categories/package_development.png', title: 'Development'},
  35     education   : {icon: 'categories/applications-sience.png', title: 'Education'},
  36     games       : {icon: 'categories/package_games.png',       title: 'Games'},
  37     graphics    : {icon: 'categories/package_graphics.png',    title: 'Graphics'},
  38     network     : {icon: 'categories/package_network.png',     title: 'Network'},
  39     multimedia  : {icon: 'categories/package_multimedia.png',  title: 'Multimedia'},
  40     office      : {icon: 'categories/package_office.png',      title: 'Office'},
  41     system      : {icon: 'categories/package_system.png',      title: 'System'},
  42     utilities   : {icon: 'categories/package_utilities.png',   title: 'Utilities'},
  43     unknown     : {icon: 'categories/applications-other.png',  title: 'Unknown'}
  44   };
```

> Wouldn't it be nicer if all unknown comes in Other?

Do you mean replacing the label with "Other" instead of "Unknown" ? It might be prettier

> How about creating a new categorie if unknown?

I don't think I will support any custom-defined categories. Mostly because of locale reasons.

**Comment by livep2000** [comment]
Okay, cannot find the parts where i saw 'other'.... it was late :)

Imre

**Comment by andersevenrud** [comment]
If you come by it, notify me. Maybe I made a mistake somewhere (It is very, very likely) :P

**Comment by andersevenrud** [comment]
> It seems i'm responsible for the little buggy's.

That is actually a good thing. I love me some issues :)

**Comment by MrSchism** [comment]
> Do you mean replacing the label with "Other" instead of "Unknown" ? It might be prettier

And more reasonable.  Either 'Other' or 'Misc.' would be a better option.

**Comment by andersevenrud** [comment]
Continued in #49

**Comment by andersevenrud** [comment]
@livep2000 You are correct... you saw "Other" somewhere. It looks like I actually thought of this one time but somehow forgot it :smile: Nice catch! It's been merged

https://github.com/andersevenrud/OS.js-v2/pull/110
