### ISSUE TITLE
How to disable demo user on locally hosted OS.js?

### ISSUE THREAD

**Issue by ComputeLinux** [andersevenrud/OS.js-v2#120]
Title.
AKA enable register/logon

**Comment by ComputeLinux** [comment]
like, what handler is it

**Comment by andersevenrud** [comment]
You can use the "example" handler that is included. It's named this way since it's purely an example on how you can do it (but still works fine).

I just updated the docs since they were outdated. Please give them a go and report back if you have any problems or questions.

PHP only at the moment though... I haven't found any time to make one for Node yet :(

https://github.com/andersevenrud/OS.js-v2/blob/master/doc/example-handler.md

**Comment by andersevenrud** [comment]
I just updated them again. Missed something

**Comment by ComputeLinux** [comment]
Here's a good mile stone: Beta 1 should have node login support

**Comment by andersevenrud** [comment]
Beta 1 is definately the target to have this in place, including a lot of other stuff. A problem is that I work on this entirely alone (except for the contributors that provide language updates etc.) and I'm very busy with work as of late... so it might take a while :/ My goal is to have a beta this fall/early winter. So stay tuned! :)

**Comment by andersevenrud** [comment]
Related to: #11

**Comment by andersevenrud** [comment]
I have just added the nodejs example handler to the repo.

Requirements:
- `npm install mysql`
- Follow http://os.js.org/doc/tutorials/create-handler.html

**Comment by ht68** [comment]
hi i'm active mysql handler, but show error message 

APIUser::login()
Error: Cannot enqueue Query after fatal error.
