### ISSUE TITLE
New package combined.js error

### ISSUE THREAD

**Issue by sercul** [andersevenrud/OS.js-v2#157]
Tried to create new Application with this tutorial http://os.js.org/doc/tutorials/create-application.html
Everything default, but I am getting error when I click on application link on main menu:

Application 'TestApp' preload error: 
/packages/default/test/combined.js

**Comment by andersevenrud** [comment]
It looks like I need to add some more info to my INSTALL file, because this comes up very often :)

You are running with the `dist` build which requires you to rebuild if you add/modify something in the code. If you want to rebuild just your package simply do `grunt packages:default/MyPackageName`.

If you use `dist-dev` you don't have to do this, and is very usefull for development purposes. This will make OS.js run straight from source.

**Comment by andersevenrud** [comment]
Please let me know if this solved your problem or if you are still wondering about something :)

**Comment by sercul** [comment]
Yes, this works, thanks. More questions to come)

**Comment by sercul** [comment]
@andersevenrud  Not sure if I can write here, but I followed tutorial from http://os.js.org/doc/tutorials/create-application-continued.html and it shows error when clicking "My label" button:

UIScheme.prototype.find@http://localhost:8000/client/javascript/gui/_scheme.js:310:1
ApplicationprotontestWindow.prototype.init/<@http://localhost:8000/packages/default/protontest/main.js:70:5
OSjs.Utils.$bind/cbNormal@http://localhost:8000/client/javascript/utils.js:1396:9

**Comment by andersevenrud** [comment]
@sercul Yeah. That tuturoial needs some updates and I have totally missed some errors in it :( Sorry about that.

```

  scheme.find(this, 'MyButtonOne').on('click', function() {
    alert(scheme.find(this, 'Text').get('value')); // <-- Change to 'self' instead of this
  });


```

**Comment by andersevenrud** [comment]
I fixed those mistakes in the documentation. Thanks for letting me know

**Comment by andersevenrud** [comment]
Closing issue because of idle-time
