### ISSUE TITLE
Tetris in iOS Safari expects keyboard input

### ISSUE THREAD

**Issue by mgmoody42** [andersevenrud/OS.js-v2#218]
Tetris in iOS is not very friendly expecting my iPad to have a keyboard. Maybe there is another way to make it work without a keyboard? Maybe someone will take it up.

**Comment by andersevenrud** [comment]
So far touch-support only extends to the Core and GUI. Some applications (like Tetris) has not been updated for this (hence why it is in the experimental repository).

Since this is related to a separate repository, I will close this issue.

I've made sure to make a note of it in the official touch-compabilty issue #112 . Thanks for reporting! :)
