### ISSUE TITLE
[GUI] ListView resize column bug(s)

### ISSUE THREAD

**Issue by zqqq** [andersevenrud/OS.js-v2#74]
listview.js line 250 

```javascript
      if ( typeof colref.resizable === 'undefined' || colref.resizable === true ) {
        if ( i < (l-i) ) { //err
          resizer           = document.createElement('div');
          resizer.className = 'Resizer';
          label.appendChild(resizer);
        }
      }
      //change i to 1
      if ( typeof colref.resizable === 'undefined' || colref.resizable === true ) {
        if ( i < (l-1) ) { //ok
          resizer           = document.createElement('div');
          resizer.className = 'Resizer';
          label.appendChild(resizer);
        }
      }

**Comment by andersevenrud** [comment]
@zqqq Thanks. I think I might have been slightly intoxicated when writing that. I uncovered a completely separate bug related to this that needs to be fixed first for this to work (Invisible columns are counted and that makes **i < (l-1)** always true)

I am going to look into the column resize some more because it does not behave nicely. Like when you resize the "MIME" column in File Manager the column moves to the left and expands at the same time. It should only expand.
