### ISSUE TITLE
[VFS] File Locking

### ISSUE THREAD

**Issue by MrSchism** [andersevenrud/OS.js-v2#86]
We need a file locking mechanism.  In testing Writer, I opened a document in two browsers and followed this procedure:

1. Open OS.js/Writer in Firefox
2. Open OS.js/Writer in Chrome
3. Save file in Firefox
4. Open in Chrome
5. Edit in Firefox (and save).
6. Save in Chrome.

There is no notice provided to Chrome that the document has been updated or is even opened.  The end result is that it gets returned to the original state (Step 3).

**Comment by andersevenrud** [comment]
The VFS storage module used by default does not have such a thing. It's just a pure proxy for the system filesystem commands.

My thoughts on options:

1. Create a purely virtual filesystem module that operates in a database and stores files in a blob-tree.
2. Configuring the server (Linux and BSD both have utilities for this), then make OS.js report *file open* and *file close* requests to the API that in turn runs a command-line or something.
3. Another option is to simply have table that contains a list of files that are currently open in the backend. Using the same report requests as mentioned in *2*

I think option *3* is the simplest route to go since it does not involve adding anything new, except a simple lookup-table that runs on every write() request (simply throws an exception).

**Comment by andersevenrud** [comment]
Also, I see this as less of a problem in an actual production environment. Users cannot touch eachother files, and you'd be warned if opening another session that you might experience some boo boo-s.

**Comment by MrSchism** [comment]
True, until you get to directories holding shared resources (typically music or video, but occasionally documents).

I think that the third option is probably best.

**Comment by andersevenrud** [comment]
> On an aside, sometimes saved files are seen as having a MIME type of "undefined" after saving.

Where ? If you can replecate this, please open an issue.

**Comment by andersevenrud** [comment]
> True, until you get to directories holding shared resources (typically music or video, but occasionally documents).

There is a shared "folder" in OS.js already. I'm thinking about disabling it by default and leaving it as an option.

**Comment by MrSchism** [comment]
Regarding the Undefined MIMEtype, it happened on step 4 occasionally, in either home or shared.

Regarding the shared folder, if we get a lock set up, it should resolve the issue entirely.  Better to have a functional feature people might not need than a broken one people might want.

**Comment by andersevenrud** [comment]
Note to self: There is no actual way of knowing when OS.js "closes" a file since it does not stream the files or stuff like that. The actual application would have to report when it closes or changes the open file, and as a fall-back have a timeout (so after that it becomes a *first served, first get* kind of thing)

**Comment by andersevenrud** [comment]
I've thought about this, and it's not much one can do when working with VFS abstration. The best I can do with how it works now is to check the last written timestamp of a file and alert the user that it will overwrite any of these changes.

Moved tasks to #49. I'm cleaning up issues :)

**Comment by RickGlimmer** [comment]
I am currently busy writing a VFS for IIS and i would probably use something like file history. The locking is very error prone so just storing each modification would at least prevent data being lost.
