### ISSUE TITLE
Official App Store

### ISSUE THREAD

**Issue by andersevenrud** [andersevenrud/OS.js-v2#99]
OS.js got support for user-installable applications a while back.

You can install official packages from the *Settings* application. There is no packages here yet though, because there is no site to submitt packages to.

The closest thing currently, is this issue: *Package and application submissions* #81

Here is the package list: http://andersevenrud.github.io/OS.js-v2/store/packages.json

The store will be up at: http://andersevenrud.github.io/OS.js-v2/store/

- [x] Add package managment to Settings application
- [ ] Create a site for submitting packages from user (@junland has started on this)
- [ ] Create a site API

**Comment by rubengc** [comment]
This could be the strongest part of the OS, because if people are encouraged to develop apps (like a MySQL manager, web server manager, or native system management) OSjs could replace many management panels, even become an ideal for installation in machines with limited resources as raspberry pi

Another great feature of the store,, can be the download/submit of new themes

**Comment by andersevenrud** [comment]
@rubengc 

> OSjs could replace many management panel

This was the original intent of OS.js actually.

> can be the download/submit of new themes

Yep. That was a part of the idea with the store :)

**Comment by MrSchism** [comment]
I just had a crazy idea.  I know it's *possible* but probably unlikely.

Why not just use a separate public repo for the store itself and have each directory in the repo's primary folder be its own package?

Like `andersevenrud/OSstore/packages/{package1,package2,package3,...}` or even
`andersevenrud/OSstore/v2/packages/{package1,package2,package3,...}` (to futureproof the repo a bit).

That way the repo page can have a clean, accessible landing page (readme.md) and a single file (per version supported in the store) which would contain the list of every package in the /packages directory.  This file could be removed, but it would create a lot of strain every time the Store loads... because it would have to scrape every folder in the package directory.

Then it'd be a matter of getting it from the git repo.  You could either do raw files or fetch using git (from either the underlying OS or using a git-js library).

**Comment by andersevenrud** [comment]
@MrSchism That is how the package system actually works right now, and I use it on the store too. Only difference is that store packages come zipped when you ask for one over the API.

Also, no scraping is actually needed since I use a manifest for all packages within a certain repository. This way all the info required to run them are "cached".

Or I might be misunderstanding you entirely :P

**Comment by MrSchism** [comment]
You're understanding me spot on.  I wasn't certain how it worked exactly.  I was more or less suggesting the following:

1. Move the store to its own repository
2. Make a directory in the repository for every store-aware version of OS.js (so v2 onward).
3. Add a manifest in the version's directory.
4. Have the store app parse the manifest.

So, does the underlying OS do the git fetch or do you use a javascript library to grab it?

**Comment by andersevenrud** [comment]
@MrSchism Yeah, that is how it works basically, but the store is a private repo atm.

```
{repository}/{package}/package.json <- Application manifest
{repository}/{package}.zip <- Downloadable
{repository}/packages.json <- Collection of all packages manifest
```

> So, does the underlying OS do the git fetch or do you use a javascript library to grab it?

You have to do this manually at the moment. Also, when installing from store you will not get the repository, but download the zip package. Since the manifests include version stamps it is fully possible to automate the update process with an in-desktop job. OS.js has support for "Services" to run cronjob-like stuff. I just have not found any time for this... also there have been next to none package submissions, so it became kind of down-prioritized.

**Comment by junland** [comment]
@andersevenrud I can go ahead and write up a front page and maybe a mockup of a app page for packages. I'm thinking of using Semantic UI but I wanted to get your input on a frontend. I figured instead of starting from scratch I would just use a already built front-end.

**Comment by andersevenrud** [comment]
@junland Sure :) I have not given it that much thought... so I'm open for ideas here.

**Comment by junland** [comment]
@andersevenrud Awesome, I'll probably just start with a couple of example landings and we can go off from there.

**Comment by junland** [comment]
![webstore1](https://cloud.githubusercontent.com/assets/9792545/8767474/b109ea4a-2e23-11e5-9f74-24c80fdeaf2d.PNG)

Here is a very rough mockup of the front landing of the webstore. It's using Materialize as the front end framework. I can go ahead and create a repo for the store and then you can merge it on to your repo @andersevenrud. Still haven't figured out scripting and linking stuff, it's not really my forte but I try todo the best I can.

**Comment by andersevenrud** [comment]
@junland Looks pretty sweet! You can use the official logos if you want (in *doc* directory of this repo).

You can fork this repo and create a pull request. I think that is the simplest way to import your work :)

https://github.com/andersevenrud/OS.js-v2-store-website

> Still haven't figured out scripting and linking stuff, it's not really my forte but I try todo the best I can.

Scripting of what ? :)

**Comment by junland** [comment]
Awesome, I'll go ahead and do that.

>Scripting of what ? :)

Getting the packages read from the package repo. :)

**Comment by andersevenrud** [comment]
I was actually thinking about creating a REST service for the store that you simply make AJAX requests to... so the website is just a standalone web app. I like keeping stuff like this very modular.

But if you want to look at it: What you want to do is to create a script that digests all the repos and fills a [relation] database (sql) with all the package manifest data (package.json). Then retrieve the packages (and filter/search) with queries.

**Comment by junland** [comment]
Alright, I'm looking into API's as we speak lol.

**Comment by andersevenrud** [comment]
@junland This issue has been moved to: https://github.com/andersevenrud/OS.js-v2-store-website/issues/3
